package com.asiainfo.demo.domain;

import java.math.BigDecimal;

public class Employee {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ZG.TB_EMPLOYEE.EMP_ID
     *
     * @mbg.generated Sun Feb 12 20:26:14 CST 2017
     */
    private BigDecimal empId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ZG.TB_EMPLOYEE.EMP_NAME
     *
     * @mbg.generated Sun Feb 12 20:26:14 CST 2017
     */
    private String empName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ZG.TB_EMPLOYEE.EMP_TYPE
     *
     * @mbg.generated Sun Feb 12 20:26:14 CST 2017
     */
    private String empType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ZG.TB_EMPLOYEE.EMP_EMAIL
     *
     * @mbg.generated Sun Feb 12 20:26:14 CST 2017
     */
    private String empEmail;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ZG.TB_EMPLOYEE.EMP_PHONE
     *
     * @mbg.generated Sun Feb 12 20:26:14 CST 2017
     */
    private String empPhone;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ZG.TB_EMPLOYEE.EMP_ID
     *
     * @return the value of ZG.TB_EMPLOYEE.EMP_ID
     *
     * @mbg.generated Sun Feb 12 20:26:14 CST 2017
     */
    public BigDecimal getEmpId() {
        return empId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ZG.TB_EMPLOYEE.EMP_ID
     *
     * @param empId the value for ZG.TB_EMPLOYEE.EMP_ID
     *
     * @mbg.generated Sun Feb 12 20:26:14 CST 2017
     */
    public void setEmpId(BigDecimal empId) {
        this.empId = empId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ZG.TB_EMPLOYEE.EMP_NAME
     *
     * @return the value of ZG.TB_EMPLOYEE.EMP_NAME
     *
     * @mbg.generated Sun Feb 12 20:26:14 CST 2017
     */
    public String getEmpName() {
        return empName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ZG.TB_EMPLOYEE.EMP_NAME
     *
     * @param empName the value for ZG.TB_EMPLOYEE.EMP_NAME
     *
     * @mbg.generated Sun Feb 12 20:26:14 CST 2017
     */
    public void setEmpName(String empName) {
        this.empName = empName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ZG.TB_EMPLOYEE.EMP_TYPE
     *
     * @return the value of ZG.TB_EMPLOYEE.EMP_TYPE
     *
     * @mbg.generated Sun Feb 12 20:26:14 CST 2017
     */
    public String getEmpType() {
        return empType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ZG.TB_EMPLOYEE.EMP_TYPE
     *
     * @param empType the value for ZG.TB_EMPLOYEE.EMP_TYPE
     *
     * @mbg.generated Sun Feb 12 20:26:14 CST 2017
     */
    public void setEmpType(String empType) {
        this.empType = empType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ZG.TB_EMPLOYEE.EMP_EMAIL
     *
     * @return the value of ZG.TB_EMPLOYEE.EMP_EMAIL
     *
     * @mbg.generated Sun Feb 12 20:26:14 CST 2017
     */
    public String getEmpEmail() {
        return empEmail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ZG.TB_EMPLOYEE.EMP_EMAIL
     *
     * @param empEmail the value for ZG.TB_EMPLOYEE.EMP_EMAIL
     *
     * @mbg.generated Sun Feb 12 20:26:14 CST 2017
     */
    public void setEmpEmail(String empEmail) {
        this.empEmail = empEmail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ZG.TB_EMPLOYEE.EMP_PHONE
     *
     * @return the value of ZG.TB_EMPLOYEE.EMP_PHONE
     *
     * @mbg.generated Sun Feb 12 20:26:14 CST 2017
     */
    public String getEmpPhone() {
        return empPhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ZG.TB_EMPLOYEE.EMP_PHONE
     *
     * @param empPhone the value for ZG.TB_EMPLOYEE.EMP_PHONE
     *
     * @mbg.generated Sun Feb 12 20:26:14 CST 2017
     */
    public void setEmpPhone(String empPhone) {
        this.empPhone = empPhone;
    }

	@Override
	public String toString() {
		return "Employee [empId=" + empId + ", empName=" + empName + ", empType=" + empType + ", empEmail=" + empEmail
				+ ", empPhone=" + empPhone + "]";
	}
    
    
}